### ISSUE TITLE
I would like to see some foundations for debugger

### ISSUE THREAD

**Issue by sangdth** [ashincoder/StarVim#15]
**Is your feature request related to a problem? Please describe.**
Recently I've been trying to implement debugger for neovim 0.5, found out it's quite not easy and some of them have a huge lag behind VSCode, for example, the `vscode-js-debugger` is the client in which currently does not work out of the box with `nvim-dap`.

**Describe the solution you'd like**
I don't expect this repo to solve this issue, it's bigger than we can handle, instead, suggest some way so it allows us to integrate a debugger easier. Still not sure how to do it, this is not my area though.

**Describe alternatives you've considered**
I don't know.

**Additional context**
I'm working mostly with javascript/typescript/react, and sometimes Python, I think they are also quite popular, so at least 2 debugger for javascript and python is good to start.

**Screenshot**
I don't have. I copied this image from a blog post about vimspector
<img width="1680" alt="vimspector-overview" src="https://user-images.githubusercontent.com/1083478/126146085-10e3d9ed-97ff-494d-8066-53335b664a38.png">

**Comment by ashincoder** [comment]
Yeah there is a plugin called [dap.nvim](https://github.com/mfussenegger/nvim-dap). I will be implementing this feature too.

**Comment by ashincoder** [comment]
@sangdth I tried to implement dap.nvim in StarVim but it is getting more complexed than ever. If you want a neovim ide with dap default try https://github.com/ChristianChiarulli/LunarVim

**Comment by sangdth** [comment]
Thank you, that project looks interesting!
