### ISSUE TITLE
No syntax highlighting for js files containing jsx

### ISSUE THREAD

**Issue by 123MayankSharma** [ashincoder/StarVim#21]
When i open a js file which has normal javascript + jsx the javascript parts are highlighted normally but the jsx parts are not getting highlighted. 

1. Make a react project 
2. In the src folder open app.js file
3. Javascript is highlighted normally but jsx is not getting highlighted 

I have added the image below:
![svim](https://user-images.githubusercontent.com/61783895/130582805-d3fcd540-f89b-47fd-810a-18eb1f9571a1.png)

I expect the jsx portion to get highlighted just like the javascript part. 

 - Operating System-Arcolinux 21.07
 - Terminal- xfce4-terminal 
 - Version of Neovim-0.5.0

I have `:TSInsalled` javascript typescript and html already

In my older config which also uses lsp and treesitter the syntax highlighting off jsx code in a js file happens just fine

**Comment by ashincoder** [comment]
Could u take a screenshot of it.

**Comment by 123MayankSharma** [comment]
@ashincoder i have added a screenshot to the original question.

**Comment by ashincoder** [comment]
Yeah I see.. now.

**Comment by ashincoder** [comment]
@123MayankSharma have u tried out NvChad. https://github.com/NvChad/NvChad, they have made me a member of the organization so I am working on it. It would be great if u try it out. It also has user_config so it is user preferable...

**Comment by 123MayankSharma** [comment]
Awesome! Thanks for your suggestions! Will look it into it😁
