### ISSUE TITLE
I made you a logo

### ISSUE THREAD

**Issue by Thomashighbaugh** [ashincoder/StarVim#25]
As you can see I have made you a logo, since you seemed to want one according to the README for the project. I made it in like two seconds, so I understand if you don't want to use it but thought it turned out OK for what it is. 

The large star is an image of the sun taken from Google than turned blue and the background is a star field randomly selected from Google. Between each is a semi-transparent black layer to help the text stand out and the font used is `Trans-America Chrome`  which comes in the [Trans-America pack from DaFont](https://www.dafont.com/trans-america.font), which I personally think looks pretty good but I have idiosyncratic tastes. 

If you do use it, all I ask is you put a link to my profile somewhere on your README for the project, just as proof to others/make it something I can write on resumes. 

![starvim](https://user-images.githubusercontent.com/32242061/132290037-ac519995-1965-4b1c-a67a-18fb87043a16.png)

**Comment by ashincoder** [comment]
sure I will.
