### ISSUE TITLE
A logo is needed

### ISSUE THREAD

**Issue by ashincoder** [ashincoder/StarVim#3]
If anyone has any good ideas for the logo. Make sure to post it here.

**Comment by im-yuria** [comment]
I made a logo and I want to send it to you. How can I do this?

**Comment by ashincoder** [comment]
what format is it in.

**Comment by ashincoder** [comment]
svg or png ?

**Comment by im-yuria** [comment]
Png

**Comment by ashincoder** [comment]
u can just drag and drop here

**Comment by im-yuria** [comment]
![SVim logo](https://user-images.githubusercontent.com/88542935/132243653-d181d4bf-eeb2-4eaf-9c71-d192b52e0c5c.png)

**Comment by ashincoder** [comment]
Man this is great. Thank you very much for ur time.

**Comment by im-yuria** [comment]
u welcome :D
